### ISSUE TITLE
master / detail --> selection / detail

### ISSUE THREAD

**Issue by UXGerda** [aposin/inclusive-coding-glossary#2]
"**Master / detail**" is currently the name for a design pattern where the user can make a selection and the UI shows additional information for this selection. For the open insurance platform UI this may happen 
* within one viewed subchapter / page (e.g. selection from a table, some fields show additional information for the selected entry) or
* spanning a whole chapter, where a list is displayed at the beginning of a chapter / top of the side-tab entries and the whole structure of subchapters / side-tabs may change depending on the selection in that first list. The selected entry of the list is displayed in the so-called **Master row** at the top of the content.

**Proposal**:
In order to  replace the term master and to better express the idea of the concept, replace 
* **Master / detail** with **selection / detail**
* **Master row** with **selection row**.

**Consequences:**
For new UI project: 
* change in guidelines, styleguide and documentation./
* code: tbd

For current UI:
* tbd

**Comment by MarRothm** [comment]
I like selection/detail. Can we check what others think?

Btw. ABS and Airwave are not used here 😊

**Comment by holzerma** [comment]
**selection / detail** seems legit, also the internal feedback i gathered is ok with that so far.

**Comment by MarRothm** [comment]
then let's add it to the list
